baseURL = 'https://yourusername.github.io/'
title = 'My Portfolio'
theme = 'PaperMod'

pagination.pagerSize = 5
enableRobotsTXT = true
languageCode = 'en-us'

[menu]

  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 1

  [[menu.main]]
    identifier = 'projects'
    name = 'Projects'
    url = '/projects/'
    weight = 2

  [[menu.main]]
    identifier = 'posts'
    name = 'Blog'
    url = '/posts/'
    weight = 3

  [[menu.main]]
    identifier = 'contact'
    name = 'Contact'
    url = '/contact/'
    weight = 4