baseURL = 'https://raoshridhar90.github.io/my-portfolio/'
title = 'My Portfolio'
theme = 'PaperMod'

pagination.pagerSize = 5
enableRobotsTXT = true
languageCode = 'en-us'

# normalize paths so project sites work
relativeURLs = true
canonifyURLs = true

[menu]

  [[menu.main]]
    name = 'About'
    pageRef = 'about'
    weight = 1

  [[menu.main]]
    name = 'Projects'
    pageRef = 'projects'   # section: content/projects/_index.md
    weight = 2

  [[menu.main]]
    name = 'Blog'
    pageRef = 'posts'      # section: content/posts/_index.md
    weight = 3

  [[menu.main]]
    name = 'Contact'
    pageRef = 'contact'
    weight = 4
